name: recsys
channels:
  - main
  - conda-forge
  - defaults
dependencies:
  - boost=1.73.0
  - brotlipy=0.7.0
  - ca-certificates=2022.5.18.1
  - certifi=2022.5.18.1
  - cffi=1.15.0
  - charset-normalizer=2.0.12
  - cryptography=37.0.2
  - idna=3.3
  - intel-openmp=2022.1.0
  - libblas=3.9.0
  - libboost=1.73.0
  - libcblas=3.9.0
  - liblapack=3.9.0
  - lightfm=1.16
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - mkl=2022.0.0
  - msys2-conda-epoch=20160418
  - numpy=1.22.4
  - openssl=1.1.1o
  - pip=21.2.4
  - py-boost=1.73.0
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.9.12
  - python_abi=3.9
  - requests=2.27.1
  - scipy=1.8.1
  - setuptools=61.2.0
  - sqlite=3.38.3
  - tbb=2021.5.0
  - urllib3=1.26.9
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.37.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xz=5.2.5
  - zlib=1.2.12
  - zstd=1.4.9
  - pip:
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - altair==4.2.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.0.5
    - async-timeout==4.0.2
    - attrs==21.4.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.0
    - blinker==1.4
    - cachetools==5.2.0
    - click==8.0.4
    - colorama==0.4.4
    - debugpy==1.6.0
    - decorator==5.1.1
    - defusedxml==0.7.1
    - entrypoints==0.4
    - executing==0.8.3
    - fastjsonschema==2.15.3
    - frozenlist==1.3.0
    - gitdb==4.0.9
    - gitpython==3.1.27
    - importlib-metadata==4.11.4
    - ipykernel==6.13.0
    - ipython==8.4.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.0
    - jedi==0.18.1
    - jikanpy==4.3.2
    - jinja2==3.1.2
    - joblib==1.1.0
    - jsonschema==4.5.1
    - jupyter-client==7.3.1
    - jupyter-core==4.10.0
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==1.1.0
    - markupsafe==2.1.1
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - multidict==6.0.2
    - nbclient==0.6.4
    - nbconvert==6.5.0
    - nbformat==5.4.0
    - nest-asyncio==1.5.5
    - notebook==6.4.11
    - packaging==21.3
    - pandas==1.4.2
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pickleshare==0.7.5
    - pillow==9.1.1
    - prometheus-client==0.14.1
    - prompt-toolkit==3.0.29
    - protobuf==3.20.1
    - psutil==5.9.1
    - pure-eval==0.2.2
    - pyarrow==8.0.0
    - pydeck==0.7.1
    - pygments==2.12.0
    - pympler==1.0.1
    - pyparsing==3.0.9
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - pytz==2022.1
    - pytz-deprecation-shim==0.1.0.post0
    - pywin32==304
    - pywinpty==2.0.5
    - pyzmq==23.0.0
    - scikit-learn==1.1.1
    - semver==2.13.0
    - send2trash==1.8.0
    - simplejson==3.17.6
    - six==1.16.0
    - smmap==5.0.0
    - soupsieve==2.3.2.post1
    - stack-data==0.2.0
    - streamlit==1.9.2
    - terminado==0.15.0
    - threadpoolctl==3.1.0
    - tinycss2==1.1.1
    - toml==0.10.2
    - toolz==0.11.2
    - tornado==6.1
    - traitlets==5.2.2.post1
    - typing-extensions==4.2.0
    - tzdata==2022.1
    - tzlocal==4.2
    - validators==0.19.0
    - watchdog==2.1.8
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.6.0
    - yarl==1.7.2
    - zipp==3.8.0
    - wincertstore=0.2
    - m2w64-gcc-libs-core=5.3.0
    - m2w64-gcc-libgfortran=5.3.0
    - msys2-conda-epoch=20160418
    - vc=14.2
    - win_inet_pton=1.1.0
    - vs2015_runtime=14.27.29016
    - intel-openmp=2022.1.0
    - m2w64-libwinpthread-git=5.0.0.4634.697f757
    - m2w64-gcc-libs=5.3.0
    - m2w64-gmp=6.1.0